### ISSUE TITLE
jinja2-style license identifier causes lint to fail

### ISSUE THREAD

**Issue by mxmehl** [fsfe/reuse-tool#170]
A jinja2 file causes a `reuse lint` of this repo to fail:

```
reuse._util - ERROR - Could not parse 'GPL-3.0-or-later #'
reuse.report - ERROR - Unexpected error occurred while parsing 'tests/resources/fake_repository/src/source_code.jinja2'
KeyError: 'path'
# READ ERRORS

Could not read:
* tests/resources/fake_repository/src/source_code.jinja2


# SUMMARY

* Bad licenses:
* Deprecated licenses:
* Licenses without file extension:
* Missing licenses:
* Unused licenses:
* Used licenses: Apache-2.0, CC-BY-SA-4.0, CC0-1.0, GPL-3.0-or-later
* Read errors: 1
* Files with copyright information: 65 / 65
* Files with license information: 65 / 65

Unfortunately, your project is not compliant with version 3.0 of the REUSE Specification :-(
```

The file causing this contains the following:

```
{# SPDX-FileCopyrightText: 2017 Mary Sue #}
{# SPDX-License-Identifier: GPL-3.0-or-later #}

<p>Hello, world!</p>
```

Probably needs some tweaking of the license parser.

**Comment by carmenbianca** [comment]
Already fixed in master ;)

#162

**Comment by mxmehl** [comment]
Ah right sorry, I've been using an older version.

So the API will still show that this repo is non-complicant since it's based on the latest release (which generally is a good idea I think). But perhaps we can find a good time to release 0.8.1 soon-ish
